"use client";

import localFont from "next/font/local";
import "./globals.css";
import SideNav from "./navigation";
import { createTheme, MantineProvider, ColorSchemeScript } from "@mantine/core";
import "@mantine/core/styles.css";
import { Provider } from "react-redux";
import store from "../app/_redux/store";
import BasePageTab from "components/baseComponent/BasePageTab";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const theme = createTheme({
  /** Put your mantine theme override here */
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Book Store</title>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* <ColorSchemeScript /> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}>
          <MantineProvider theme={theme}>
            <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
              <div className="h-full">
                <SideNav />
              </div>
              <div className="flex-grow">{children}</div>
            </div>
          </MantineProvider>
        </Provider>
      </body>
    </html>
  );
}
